---
kind: Job
apiVersion: batch/v1
metadata:
  name: check
  namespace: bgd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      name: checker
      labels:
        job-name: check
    spec:
      containers:
        - name: ose-cli
          image: 'registry.redhat.io/openshift4/ose-cli:v4.11'
          command:
            - sh
            - '-c'
            - >-
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}''
              http://bgd.bgd.svc:8080)" != "200" ]]; do echo 'Looking for the
              200 code' && sleep 5; done
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  completionMode: NonIndexed
  suspend: false
